language: node_js
node_js:
  - "node"
  - "lts/*"
cache:
  directories:
    - "node_modules"
script:
  - npm run test:cover
  - npm run build
after_success:
  # Send coverage data to coveralls.
  - npm run test:cover:CI

